<div>
    <div class="page-title"><div><h1>Approvals</h1><p>Manager workflow for submitted timesheets and PTO requests.</p></div></div>
    @if($message)<div class="notice {{ $messageType }}">{{ $message }}</div>@endif
    <div class="panel panel-pad" style="margin-bottom:16px"><div class="field"><label>Review note for the next action</label><textarea class="textarea" wire:model="notes" placeholder="Optional reason or instruction…"></textarea></div></div>
    <div class="grid grid-2">
        <div class="panel"><div class="toolbar"><div><h2>Timesheets</h2><div class="muted">Submitted and waiting for approval</div></div><span class="badge badge-blue">{{ $timesheets->count() }}</span></div><div class="table-wrap"><table><thead><tr><th>Employee</th><th>Period</th><th>Total</th><th>Action</th></tr></thead><tbody>@forelse($timesheets as $sheet)<tr><td>{{ $sheet->employee->full_name }}</td><td>{{ $sheet->period_start->format('d M') }} – {{ $sheet->period_end->format('d M') }}</td><td>{{ number_format($sheet->total_hours,2) }}h</td><td><div class="actions"><button wire:click="reviewTimesheet({{ $sheet->id }}, 'approve')" class="btn btn-primary btn-small">Approve</button><button wire:click="reviewTimesheet({{ $sheet->id }}, 'reject')" class="btn btn-danger btn-small">Reject</button></div></td></tr>@empty<tr><td colspan="4"><div class="empty">No submitted timesheets.</div></td></tr>@endforelse</tbody></table></div></div>
        <div class="panel"><div class="toolbar"><div><h2>PTO requests</h2><div class="muted">Leave requests waiting for approval</div></div><span class="badge badge-yellow">{{ $ptoRequests->count() }}</span></div><div class="table-wrap"><table><thead><tr><th>Employee</th><th>Dates</th><th>Type</th><th>Action</th></tr></thead><tbody>@forelse($ptoRequests as $request)<tr><td>{{ $request->employee->full_name }}</td><td>{{ $request->starts_on->format('d M') }} – {{ $request->ends_on->format('d M Y') }}</td><td>{{ ucfirst($request->type) }}</td><td><div class="actions"><button wire:click="reviewPto({{ $request->id }}, 'approve')" class="btn btn-primary btn-small">Approve</button><button wire:click="reviewPto({{ $request->id }}, 'reject')" class="btn btn-danger btn-small">Reject</button></div></td></tr>@empty<tr><td colspan="4"><div class="empty">No pending leave requests.</div></td></tr>@endforelse</tbody></table></div></div>
    </div>
</div>
