<div>
    <div class="page-title"><div><h1>Payroll</h1><p>Generate gross-pay reports from approved weekly timesheets.</p></div></div>
    @if($message)<div class="notice {{ $messageType }}">{{ $message }}</div>@endif
    <div class="panel panel-pad" style="margin-bottom:16px"><div class="form-grid"><div class="field"><label>Period start</label><input class="input" type="date" wire:model="periodStart"></div><div class="field"><label>Period end</label><input class="input" type="date" wire:model="periodEnd"></div></div><div style="height:14px"></div><button wire:click="generate" class="btn btn-primary">Generate payroll</button></div>
    <div class="grid grid-2">
        <div class="panel"><div class="toolbar"><div><h2>Payroll runs</h2><div class="muted">Recent generated reports</div></div></div><div class="table-wrap"><table><thead><tr><th>Period</th><th>Gross</th><th>Status</th><th></th></tr></thead><tbody>@forelse($reports as $report)<tr><td>{{ $report->period_start->format('d M') }} – {{ $report->period_end->format('d M Y') }}</td><td>{{ number_format($report->total_gross_pay,2) }}</td><td><span class="badge {{ $report->status==='processed'?'badge-green':'badge-blue' }}">{{ $report->status }}</span></td><td><div class="actions"><button wire:click="$set('selectedReportId', {{ $report->id }})" class="btn btn-secondary btn-small">View</button>@if($report->status!=='processed')<button wire:click="process({{ $report->id }})" class="btn btn-primary btn-small">Process</button>@endif</div></td></tr>@empty<tr><td colspan="4"><div class="empty">No payroll runs yet.</div></td></tr>@endforelse</tbody></table></div></div>
        <div class="panel"><div class="toolbar"><div><h2>{{ $selected ? 'Report detail' : 'Payroll detail' }}</h2><div class="muted">Approved timesheets only</div></div></div>@if($selected)<div class="panel-pad"><div class="grid grid-3"><div class="mini"><strong>{{ number_format($selected->total_regular_hours,2) }}h</strong><span>Regular</span></div><div class="mini"><strong>{{ number_format($selected->total_overtime_hours,2) }}h</strong><span>Overtime</span></div><div class="mini"><strong>{{ number_format($selected->total_gross_pay,2) }}</strong><span>Gross pay</span></div></div></div><div class="table-wrap"><table><thead><tr><th>Employee</th><th>Regular</th><th>OT</th><th>Gross</th></tr></thead><tbody>@forelse($selected->items as $item)<tr><td>{{ $item->employee->full_name }}</td><td>{{ number_format($item->regular_hours,2) }}h</td><td>{{ number_format($item->overtime_hours,2) }}h</td><td>{{ number_format($item->gross_pay,2) }}</td></tr>@empty<tr><td colspan="4"><div class="empty">No approved hours matched this period.</div></td></tr>@endforelse</tbody></table></div>@else<div class="empty">Generate a report to see its items.</div>@endif</div>
    </div>
</div>
