<div>
    <div class="page-title"><div><h1>Settings</h1><p>Configure departments, shifts and overtime rules used by the tracking system.</p></div></div>
    @if($message)<div class="notice {{ $messageType }}">{{ $message }}</div>@endif
    <div class="grid grid-3">
        <div class="panel panel-pad"><div class="toolbar" style="padding:0 0 16px;border:0"><div><h2>Department</h2><div class="muted">Create a department</div></div></div><div class="field"><label>Name</label><input class="input" wire:model="departmentName"></div><div style="height:10px"></div><div class="field"><label>Code</label><input class="input" wire:model="departmentCode"></div><div style="height:10px"></div><div class="field"><label>Description</label><textarea class="textarea" wire:model="departmentDescription"></textarea></div><div style="height:10px"></div><button class="btn btn-primary" wire:click="addDepartment">Create department</button></div>
        <div class="panel panel-pad"><div class="toolbar" style="padding:0 0 16px;border:0"><div><h2>Shift</h2><div class="muted">Assign a work schedule</div></div></div><div class="field"><label>Employee</label><select class="select" wire:model="shiftEmployeeId"><option value="">Select employee</option>@foreach($employees as $employee)<option value="{{ $employee->id }}">{{ $employee->full_name }}</option>@endforeach</select></div><div style="height:10px"></div><div class="field"><label>Shift name</label><input class="input" wire:model="shiftName"></div><div style="height:10px"></div><div class="form-grid"><div class="field"><label>Start</label><input class="input" type="time" wire:model="shiftStart"></div><div class="field"><label>End</label><input class="input" type="time" wire:model="shiftEnd"></div><div class="field"><label>Break</label><input class="input" type="number" min="0" wire:model="breakMinutes"></div><div class="field"><label>Regular hours</label><input class="input" type="number" min="0" step="0.5" wire:model="regularHours"></div></div><div style="height:10px"></div><button class="btn btn-primary" wire:click="addShift">Assign shift</button></div>
        <div class="panel panel-pad"><div class="toolbar" style="padding:0 0 16px;border:0"><div><h2>Overtime rule</h2><div class="muted">Only one active rule is used.</div></div></div><div class="field"><label>Name</label><input class="input" wire:model="overtimeName"></div><div style="height:10px"></div><div class="field"><label>Weekly threshold (minutes)</label><input class="input" type="number" min="1" wire:model="thresholdMinutes"></div><div style="height:10px"></div><div class="field"><label>Multiplier</label><input class="input" type="number" min="1" step="0.05" wire:model="multiplier"></div><div style="height:10px"></div><button class="btn btn-primary" wire:click="saveOvertimeRule">Save rule</button></div>
    </div>
    <div style="height:16px"></div>
    <div class="grid grid-3">
        <div class="panel"><div class="toolbar"><div><h2>Departments</h2><div class="muted">Configured groups</div></div></div><div class="table-wrap"><table><thead><tr><th>Name</th><th>Code</th><th>Employees</th></tr></thead><tbody>@forelse($departments as $department)<tr><td>{{ $department->name }}</td><td>{{ $department->code ?? '—' }}</td><td>{{ $department->employees()->count() }}</td></tr>@empty<tr><td colspan="3"><div class="empty">None.</div></td></tr>@endforelse</tbody></table></div></div>
        <div class="panel"><div class="toolbar"><div><h2>Shifts</h2><div class="muted">Latest assignments</div></div></div><div class="table-wrap"><table><thead><tr><th>Employee</th><th>Shift</th><th>Hours</th></tr></thead><tbody>@forelse($shifts as $shift)<tr><td>{{ $shift->employee->full_name }}</td><td>{{ $shift->name }}<div style="color:#66748a;font-size:9px">{{ substr($shift->starts_at,0,5) }}–{{ substr($shift->ends_at,0,5) }}</div></td><td>{{ number_format($shift->regular_hours,2) }}</td></tr>@empty<tr><td colspan="3"><div class="empty">None.</div></td></tr>@endforelse</tbody></table></div></div>
        <div class="panel"><div class="toolbar"><div><h2>Overtime rules</h2><div class="muted">History of rules</div></div></div><div class="table-wrap"><table><thead><tr><th>Name</th><th>Threshold</th><th>Multiplier</th></tr></thead><tbody>@forelse($overtimeRules as $rule)<tr><td>{{ $rule->name }}</td><td>{{ number_format($rule->threshold_minutes/60,2) }}h</td><td>{{ number_format($rule->multiplier,2) }}×</td></tr>@empty<tr><td colspan="3"><div class="empty">None.</div></td></tr>@endforelse</tbody></table></div></div>
    </div>
</div>
