<div>
    <div class="page-title"><div><h1>Timesheets</h1><p>Build a weekly timesheet from closed clock entries, then submit it for review.</p></div><div class="actions"><button wire:click="previousPeriod" class="btn btn-secondary btn-small">← Previous</button><button wire:click="nextPeriod" class="btn btn-secondary btn-small">Next →</button></div></div>
    @if($message)<div class="notice {{ $messageType }}">{{ $message }}</div>@endif
    <div class="panel panel-pad">
        <div class="toolbar" style="padding:0 0 16px;border:0"><div><h2>{{ \Carbon\Carbon::parse($periodStart)->format('d M Y') }} – {{ \Carbon\Carbon::parse($periodEnd)->format('d M Y') }}</h2><div class="muted">Current selected pay period</div></div><div class="actions"><button wire:click="generate" class="btn btn-secondary">Refresh totals</button>@if($timesheet && in_array($timesheet->status,['draft','rejected']))<button wire:click="submit({{ $timesheet->id }})" class="btn btn-primary">Submit for approval</button>@endif</div></div>
        @if($timesheet)
            <div class="grid grid-4"><div class="stat-card panel"><div class="stat-label">Regular</div><div class="stat-value">{{ number_format($timesheet->regular_hours,2) }}h</div></div><div class="stat-card panel"><div class="stat-label">Overtime</div><div class="stat-value">{{ number_format($timesheet->overtime_hours,2) }}h</div></div><div class="stat-card panel"><div class="stat-label">PTO</div><div class="stat-value">{{ number_format($timesheet->pto_hours,2) }}h</div></div><div class="stat-card panel"><div class="stat-label">Total</div><div class="stat-value">{{ number_format($timesheet->total_hours,2) }}h</div></div></div>
            <div style="height:14px"></div><div class="badge {{ $timesheet->status==='approved'?'badge-green':($timesheet->status==='rejected'?'badge-red':'badge-blue') }}">{{ $timesheet->status }}</div>
        @else
            <div class="empty">No timesheet exists for this period. Click <strong>Refresh totals</strong> to generate it.</div>
        @endif
    </div>
    <div style="height:16px"></div>
    <div class="panel"><div class="toolbar"><div><h2>Week detail</h2><div class="muted">Every clock entry included in this period</div></div></div><div class="table-wrap"><table><thead><tr><th>Date</th><th>Shift</th><th>Clock in</th><th>Clock out</th><th>Total</th><th>Status</th></tr></thead><tbody>@forelse($entries as $entry)<tr><td>{{ $entry->work_date->format('D, d M') }}</td><td>{{ $entry->shift?->name ?? '—' }}</td><td>{{ $entry->clock_in->format('H:i') }}</td><td>{{ $entry->clock_out?->format('H:i') ?? '—' }}</td><td>{{ number_format($entry->hours,2) }}h</td><td><span class="badge {{ $entry->status==='closed'?'badge-green':'badge-yellow' }}">{{ $entry->status }}</span></td></tr>@empty<tr><td colspan="6"><div class="empty">No entries found for this period.</div></td></tr>@endforelse</tbody></table></div></div>
    <div style="height:16px"></div>
    <div class="panel"><div class="toolbar"><div><h2>Timesheet history</h2><div class="muted">Recent periods</div></div></div><div class="table-wrap"><table><thead><tr><th>Period</th><th>Regular</th><th>OT</th><th>Total</th><th>Status</th></tr></thead><tbody>@forelse($history as $sheet)<tr><td>{{ $sheet->period_start->format('d M') }} – {{ $sheet->period_end->format('d M Y') }}</td><td>{{ number_format($sheet->regular_hours,2) }}h</td><td>{{ number_format($sheet->overtime_hours,2) }}h</td><td>{{ number_format($sheet->total_hours,2) }}h</td><td><span class="badge {{ $sheet->status==='approved'?'badge-green':($sheet->status==='rejected'?'badge-red':'badge-blue') }}">{{ $sheet->status }}</span></td></tr>@empty<tr><td colspan="5"><div class="empty">No history yet.</div></td></tr>@endforelse</tbody></table></div></div>
</div>
